### ISSUE TITLE
Server Technologies

### ISSUE THREAD

**Issue by kenzdozz** [gtainfotech/goforit_server#3]
I wish to know. What are the reasons behind the chosen Server Technologies, especially Cassandra DB. I find it to have a fewer developer community around it and to be more difficult to use.
I would have preferred MongoDb

**Comment by gtainfotech** [comment]
Cassandra is not so unpopular. The reason for choosing Cassandra DB was the expected size of the app, as we are aiming to reach the position of top web apps used by the general public, as well as the business community. We could have used even MySQL for all I know, as YouTube, for example, has successfully done that. I invite all to dispense their opinion on this issue.

**Comment by sushilkator** [comment]
even mongo is far better for large data set, you can create multi tnant db,
and run you db server on multiple cluster.

**Comment by umarzirgham** [comment]
Yes, as far as I am concerned. I will go with mongodb because I worked on it and it is good for big data handling.

**Comment by kenzdozz** [comment]
I thought I was the only one not comfortable with cassandra, but since I am not alone, I think we should consider it

**Comment by gtainfotech** [comment]
OK. I want to listen to you all. But before proceeding, let's check this Google search page: https://www.google.com/search?ei=78xgXa7XO9PT-QbI9I_ICw&q=what+is+the+most+scalable+nosql+database&oq=what+is+the+most+scalable+nosql+database&gs_l=psy-ab.3...33684.38487..39885...1.2..0.164.846.1j6......0....1..gws-wiz.......0i71j35i39.p7GiqcSUQB8&ved=0ahUKEwjuiuP45JrkAhXTad4KHUj6A7kQ4dUDCAo&uact=5

**Comment by umarzirgham** [comment]
Okay I have read that above link and also I searched about Cassandra DB. It is similar to SQL like queries are same. So I think we can work on it and it will be new tech for us to learn and work. What you say guys?

**Comment by sushilkator** [comment]
please go through this document and decide which one is best for our application. if our data is normalized and structured then Cassandra DB best. if our data is not structured and denormalize then go for Mongo.
https://www.improgrammer.net/most-popular-nosql-database/

finally product call what we want

**Comment by umarzirgham** [comment]
Okay according to my research on CQL. 
1) Joins are not possible because it is NoSQL with columnar approach.
2) If we want to join more columns then we can apply separate queries and then manipulate data accordingly.
3) Cassandra is designed to handle real-time data produced by companies like Facebook, Instagram.

Talk about Mongodb
1) JSON format data stored in DB
2) JOINS are possible but we have to make approach of structure that we can avoid joins in Mongo.
3) For instance, one user can publish many advertisements. So instead of making 2 tables, one for user and one for advertisement. We will make one table and against user json data, we will make array of advertisement. (other server developers understand this what I am talking about).

Now our project is CRM based and normal DB is also applicable. This is what my suggestion for DB. We can further debate on it so that we all server developers will be on single page. What you say now #all?

**Comment by gtainfotech** [comment]
What do you mean by normal DB? Does it mean that we stay with Cassandra DB?

**Comment by gtainfotech** [comment]
OK, sorry. I got it. Cassandra DB it is.

**Comment by kenzdozz** [comment]
> Okay I have read that above link and also I searched about Cassandra DB. It is similar to SQL like queries are same. So I think we can work on it and it will be new tech for us to learn and work. What you say guys?

Okay, that will be nice... Something new to learn
